### ISSUE TITLE
Tor Check before scan

### ISSUE THREAD

**Issue by bandrel** [BlackBox-CSP/nmap-tor-scanner#8]
if you get a connection refused to the socks proxy create exception.

**Comment by ryman1** [comment]
still getting the error when tor isn't started. I'm on the latest master.

/usr/bin/python2.7 /root/tools/nmap-tor-scanner/nmap-tor.py --targetlist /tmp/targets.txt --portlist /tmp/ports.txt
[+] Nmap-Tor-Scanner starting up...

Unable to reach https://www.atagar.com/echo.php ((7, 'Failed to connect to localhost port 9050: Connection refused'))
[*] Exiting check tor service to see if it is started...

Process finished with exit code 1

**Comment by bandrel** [comment]
When tor is or isn't started?

Sent from my iPhone

On Oct 1, 2015, at 5:53 PM, ryman1 <notifications@github.com<mailto:notifications@github.com>> wrote:

still getting the error when tor isn't started. I'm on the latest master.

/usr/bin/python2.7 /root/tools/nmap-tor-scanner/nmap-tor.py --targetlist /tmp/targets.txt --portlist /tmp/ports.txt
[+] Nmap-Tor-Scanner starting up...

Unable to reach https://www.atagar.com/echo.php ((7, 'Failed to connect to localhost port 9050: Connection refused'))
[*] Exiting check tor service to see if it is started...

Process finished with exit code 1

—
Reply to this email directly or view it on GitHubhttps://github.com/BlackBox-CSP/nmap-tor-scanner/issues/8#issuecomment-144860480.

---

This email and any files transmitted with it are confidential and are intended for the sole use of the individual to whom they are addressed. Black Box Corporation reserves the right to scan all e-mail traffic for restricted content and to monitor all e-mail in general. If you are not the intended recipient or you have received this email in error, any use, dissemination or forwarding of this email is strictly prohibited. If you have received this email in error, please notify the sender by replying to this email.

**Comment by ryman1** [comment]
isn't

**Comment by bandrel** [comment]
This is what it is supposed to do.  Error out and not continue to scan if tor is not started.

**Comment by ryman1** [comment]
Err never mind I'm retarded.
